disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - force_try
  - identifier_name
  - implicit_getter
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - PlayerSelectionTests
